# -*- coding: utf-8 -*-
"""New end-to-end pipeline with Bosen additional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1reXLn8texluNIxunMMIKmXeKm594Rzk6
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

from pathlib import Path

DRIVE     = Path("/content/drive/MyDrive/Capstone")
MODEL_DIR = DRIVE / "trained_model"

required = [
    "entity_embeddings.npy",
    "relation_embeddings.npy",
    "entity_to_id.json",
    "relation_to_id.json",
    "mined_config.json",
    "training_metrics.json",
    "recipe_nutrients.json"
]

print("Checking model files...")
all_ok = True
for f in required:
    p = MODEL_DIR / f
    exists = p.exists()
    size   = f"{p.stat().st_size / 1e6:.1f} MB" if exists else "MISSING"
    mark   = "✅" if exists else "❌"
    print(f"  {mark} {f:<35} {size}")
    if not exists:
        all_ok = False

print()
print("✅ All files present — ready to proceed." if all_ok else "❌ Fix missing files before continuing.")

import subprocess

result = subprocess.run(
    ["find", str(DRIVE), "-name", "triples.tsv"],
    capture_output=True, text=True
)
print(result.stdout or "❌ triples.tsv not found anywhere")

# ── Update this to match the find output above ──
TRIPLES_TSV = DRIVE / "triples.tsv"  # adjust if different

print(f"Triples file : {TRIPLES_TSV}")
print(f"Exists       : {TRIPLES_TSV.exists()}")
if TRIPLES_TSV.exists():
    import subprocess
    wc = subprocess.run(["wc", "-l", str(TRIPLES_TSV)], capture_output=True, text=True)
    print(f"Line count   : {wc.stdout.strip()}")

import csv, json
from collections import defaultdict

print("Building recipe_nutrients.json from triples...")

recipe_nutrients = defaultdict(list)

with open(TRIPLES_TSV) as f:
    for head, relation, tail in csv.reader(f, delimiter="\t"):
        if relation == "PROVIDES":
            recipe_nutrients[head].append(tail)

out = MODEL_DIR / "recipe_nutrients.json"
with open(out, "w") as f:
    json.dump(recipe_nutrients, f)

print(f"✅ Done — {len(recipe_nutrients):,} recipes mapped")
print(f"   Saved to: {out}")

# Sanity check
print("\nSample:")
for recipe, nutrients in list(recipe_nutrients.items())[:3]:
    print(f"  {recipe}: {nutrients}")

import json, math, random
import numpy as np
from collections import defaultdict, Counter
from pathlib import Path
from scipy.stats import spearmanr

random.seed(42)
np.random.seed(42)

# ── Load model ──
print("Loading model...")
e   = np.load(MODEL_DIR / "entity_embeddings.npy")
r   = np.load(MODEL_DIR / "relation_embeddings.npy")
dim = e.shape[1] // 2

with open(MODEL_DIR / "entity_to_id.json")   as f: e2id = json.load(f)
with open(MODEL_DIR / "relation_to_id.json") as f: r2id = json.load(f)
with open(MODEL_DIR / "mined_config.json")   as f: cfg  = json.load(f)
with open(MODEL_DIR / "recipe_nutrients.json") as f: kg_nutrients = json.load(f)
with open(MODEL_DIR / "training_metrics.json") as f: train_metrics = json.load(f)

ec   = e[:, :dim] + 1j * e[:, dim:]
rc   = r[:, :dim] + 1j * r[:, dim:]
id2e = {v: k for k, v in e2id.items()}

ailment_map = cfg.get("AILMENT_NUTRIENT_MAP", {})
nut_norm    = cfg.get("NUTRIENT_NORMALIZE", {})

print(f"✅ Model loaded")
print(f"   Entities  : {len(e2id):,}")
print(f"   Relations : {len(r2id)}")
print(f"   Embed dim : {dim * 2}")
print(f"   Recipes with kg_nutrients : {len(kg_nutrients):,}")

# ── Helper functions ──
def resolve(name):
    for v in [name, name.lower(), name.replace(" ", "_"), name.lower().replace(" ", "_")]:
        if v in e2id:
            return v
    return None

def predict_head(relation, tail, top_k=500):
    t = resolve(tail)
    if not t or relation not in r2id:
        return []
    scores = -np.abs(ec * rc[r2id[relation]] - ec[e2id[t]]).sum(axis=1)
    ranked = np.argsort(-scores)
    return [(id2e[i], float(scores[i])) for i in ranked if id2e[i] != t][:top_k]

## Test - Diagnostic

import pandas as pd
from pathlib import Path

DRIVE   = Path("/content/drive/MyDrive/Capstone")
PARQUET = DRIVE / "df_recipe_nutrient_health_merged.parquet"

df = pd.read_parquet(PARQUET)

print(f"Shape          : {df.shape}")
print(f"Columns        : {list(df.columns)}")
print(f"Dtypes:\n{df.dtypes}")
print(f"\nFirst row:\n{df.iloc[0]}")

import pandas as pd
from pathlib import Path

print("\n" + "="*65)
print("  SECTION A — kg_nutrients ACCURACY (KG Construction Quality)")
print("="*65)

PARQUET = DRIVE / "df_recipe_nutrient_health_merged.parquet"
df = pd.read_parquet(PARQUET)
print(f"Raw rows (long format) : {len(df):,}")

# ── Pivot to wide: one recipe per row, nutrients as columns ──
print("Pivoting to recipe-level ground truth...")

gt = (
    df[df["nutrient_value"] > 0]          # only non-zero nutrients
    .groupby("Name")["fndds_nutrient_col"] # group by recipe name
    .apply(set)                            # collect set of nutrient names
    .to_dict()
)

print(f"Unique recipes in ground truth : {len(gt):,}")

# Peek at what nutrient names look like in the parquet
sample_nuts = list(list(gt.values())[0])[:5]
print(f"Sample nutrient names (parquet): {sample_nuts}")

# Peek at what nutrient names look like in kg_nutrients
sample_kg = list(list(kg_nutrients.values())[0])[:5]
print(f"Sample nutrient names (KG)     : {sample_kg}")

print("\n" + "="*65)
print("  SECTION B — kg_score CALIBRATION (Ranking Quality)")
print("="*65)

AILMENT_GROUND_TRUTH = {
    "hypertension":           ["potassium", "magnesium", "fiber"],
    "type_2_diabetes":        ["fiber", "protein", "magnesium"],
    "iron_deficiency_anemia": ["iron", "protein", "copper"],
    "osteoporosis":           ["calcium", "phosphorus", "protein"],
    "high_cholesterol":       ["fiber", "protein"],
    "obesity":                ["fiber", "protein"],
    "heart_disease":          ["potassium", "magnesium", "fiber"],
}

def ndcg_at_k(pairs, k=10):
    """NDCG@k — relevance = number of target nutrients present."""
    top_k = sorted(pairs, key=lambda x: -x[0])[:k]
    dcg   = sum(rel / np.log2(i+2) for i, (_, rel) in enumerate(top_k))
    ideal = sorted([rel for _, rel in top_k], reverse=True)
    idcg  = sum(rel / np.log2(i+2) for i, rel in enumerate(ideal))
    return dcg / idcg if idcg > 0 else 0.0

print(f"\n  {'Ailment':<30} {'Spearman ρ':>11} {'p-value':>9} {'NDCG@10':>9} {'Status'}")
print("  " + "─"*72)

all_rho, all_ndcg = [], []

for ailment, target_nuts in AILMENT_GROUND_TRUTH.items():
    key  = ailment.lower().replace(" ", "_")
    info = ailment_map.get(key, {})
    target_set = set(target_nuts)

    # Aggregate kg_scores across all target nutrients (same as UI does)
    score_agg = {}
    for raw in info.get("needs", []):
        canonical = nut_norm.get(raw, raw)
        for name, score in predict_head("PROVIDES_BY", canonical, top_k=500):
            score_agg[name] = score_agg.get(name, 0.0) + score

    if len(score_agg) < 20:
        print(f"  {ailment:<30} {'insufficient data':>30}")
        continue

    # Build (kg_score, relevance) pairs
    pairs = []
    for recipe, score in score_agg.items():
        match_count = len(set(kg_nutrients.get(recipe, [])) & target_set)
        pairs.append((score, match_count))

    kg_scores  = [p[0] for p in pairs]
    relevances = [p[1] for p in pairs]

    rho, pval   = spearmanr(kg_scores, relevances)
    ndcg_score  = ndcg_at_k(pairs, k=10)
    status      = "✅" if rho > 0.2 else "⚠ "

    all_rho.append(rho)
    all_ndcg.append(ndcg_score)

    print(f"  {ailment:<30} {rho:>11.3f} {pval:>9.4f} {ndcg_score:>9.3f}  {status}")

print()
print(f"  Mean Spearman ρ  : {sum(all_rho)/len(all_rho):.3f}  "
      f"({'✅ score predicts quality' if sum(all_rho)/len(all_rho) > 0.2 else '⚠ weak calibration'})")
print(f"  Mean NDCG@10     : {sum(all_ndcg)/len(all_ndcg):.3f}")
print()
print("  Interpretation guide:")
print("    Spearman ρ > 0.30 → kg_score strongly predicts nutrient match")
print("    Spearman ρ > 0.20 → kg_score meaningfully predicts quality")
print("    NDCG@10   > 0.70  → top-10 list is well-ranked")

print("\n" + "="*65)
print("  SECTION C — DEPLOYMENT COVERAGE")
print("="*65)

total_db     = df["Name"].nunique()          # unique recipes, not 188M rows
recipe_names = set(df["Name"].dropna().tolist())

# Coverage: recipes in DB that the KG can serve
kg_covered = sum(
    1 for name in recipe_names
    if name in kg_nutrients and len(kg_nutrients[name]) > 0
)

# Score coverage: can any ailment query return this recipe?
all_scored = set()
for ailment, info in list(ailment_map.items())[:5]:  # sample 5 ailments
    for raw in info.get("needs", []):
        canonical = nut_norm.get(raw, raw)
        for name, _ in predict_head("PROVIDES_BY", canonical, top_k=1000):
            all_scored.add(name)

scoreable_in_db = sum(1 for n in all_scored if n in recipe_names)

print(f"\n  {'Metric':<45} {'Count':>10}  {'%':>6}")
print("  " + "─"*65)
print(f"  {'Total recipes in database':<45} {total_db:>10,}")
print(f"  {'Recipes with kg_nutrients populated':<45} {kg_covered:>10,}  "
      f"{kg_covered/total_db*100:>5.1f}%")
print(f"  {'Recipes scoreable by KG (sample ailments)':<45} {scoreable_in_db:>10,}  "
      f"{scoreable_in_db/total_db*100:>5.1f}%")
print(f"  {'Coverage gap (fallback only)':<45} {total_db-kg_covered:>10,}  "
      f"{(total_db-kg_covered)/total_db*100:>5.1f}%")

# Avg nutrients per recipe
avg_nuts = sum(len(v) for v in kg_nutrients.values()) / max(len(kg_nutrients), 1)
print(f"\n  Avg kg_nutrients per recipe : {avg_nuts:.1f}")
print(f"  Recipes with 0 nutrients    : "
      f"{sum(1 for v in kg_nutrients.values() if len(v) == 0):,}")
print(f"  Recipes with 5+ nutrients   : "
      f"{sum(1 for v in kg_nutrients.values() if len(v) >= 5):,}")

coverage_pct = kg_covered / total_db * 100
print()
if coverage_pct >= 80:
    print("  ✅ Strong coverage — KG serves most users")
elif coverage_pct >= 60:
    print("  ⚠  Moderate coverage — fallback handles remainder")
else:
    print("  ❌ Low coverage — investigate name matching between KG and DB")

# How many triples are there

import json
from pathlib import Path

with open(Path("/content/drive/MyDrive/Capstone/trained_model/training_metrics.json")) as f:
    m = json.load(f)

print(f"Total triples : {m['num_triples']:,}")
print(f"Full metrics  : {json.dumps(m, indent=2)}")

